name: conda_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _x86_64-microarch-level=3
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cairo=1.18.4
  - cairomm=1.16.2
  - cairomm-1.16=1.16.2
  - cartopy=0.24.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - dbus=1.13.6
  - epoxy=1.5.10
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - geos=3.13.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - glib-tools=2.84.0
  - gmp=6.3.0
  - graph-tool=2.92
  - graph-tool-base=2.92
  - graphite2=1.3.13
  - gtest=1.16.0
  - gtk3=3.24.43
  - harfbuzz=10.4.0
  - hicolor-icon-theme=0.17
  - icu=75.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgirepository=1.84.0
  - libglib=2.84.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - librsvg=2.58.4
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.8.1
  - libxml2=2.13.7
  - libzlib=1.3.1
  - matplotlib-base=3.10.1
  - ncurses=6.5
  - numpy=2.2.4
  - openssl=3.4.1
  - packaging=24.2
  - pango=1.56.3
  - pcre2=10.44
  - pip=25.0
  - pixman=0.44.2
  - proj=9.6.0
  - pthread-stubs=0.4
  - pycairo=1.27.0
  - pycparser=2.22
  - pygobject=3.50.0
  - pyproj=3.7.1
  - pyshp=2.3.1
  - python=3.13.2
  - python_abi=3.13
  - qhull=2020.2
  - readline=8.2
  - scipy=1.15.2
  - setuptools=75.8.0
  - shapely=2.0.7
  - sigcpp-3.0=3.6.0
  - sparsehash=2.0.4
  - sqlite=3.49.1
  - tk=8.6.13
  - tzdata=2025a
  - wayland=1.23.1
  - wheel=0.45.1
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxpm=3.5.17
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xextproto=7.3.0
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - geographiclib==2.0
      - geopy==2.4.1
      - kiwisolver==1.4.8
      - networkx==3.4.2
      - pillow==11.1.0
      - pyparsing==3.2.3
      - pyqt6==6.8.1
      - pyqt6-qt6==6.8.2
      - pyqt6-sip==13.10.0
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - zstandard==0.23.0
      - zstd==1.5.6.6
